name: 'Code Quality'
description: 'Run Qodana code quality scan'

runs:
  using: "composite"
  steps:
    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v2024.3
      shell: bash
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
