name: build-test-deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK and maven cache
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: "temurin"
          cache: maven

      - name: build and test
        continue-on-error: true
        run: ./mvnw clean verify

      - name: Publish to Github Packages
        run: ./mvnw deploy -DskipTests -Dmaven.source.skip=false -Dmaven.javadoc.skip=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
