name: build-test-deploy
on:
    workflow_dispatch:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build-test-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   name: checkout the repository
                uses: actions/checkout@v4

            -   name: Set up JDK and maven cache
                uses: actions/setup-java@v4
                with:
                    java-version: '23'
                    distribution: "temurin"

            -   name: Cache Maven dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-

            -   name: build and test
                continue-on-error: true
                run: ./mvnw clean verify

            -   name: version setup (Tag or Commit Hash)
                id: git-info
                run: |
                    TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
                    if [ -z "$TAG" ]; then
                      GIT_HASH=$(git rev-parse --short HEAD)
                      echo "PROJECT_VERSION=$GIT_HASH" >> $GITHUB_ENV
                    else
                      echo "PROJECT_VERSION=$TAG" >> $GITHUB_ENV
                    fi

            -   name: Update Maven version with Git tag or hash
                run: |
                    ./mvnw versions:set -DnewVersion="${{ env.PROJECT_VERSION }}"

            -   name: Publish to Github Packages
                run: ./mvnw deploy -DskipTests -Dmaven.source.skip=false -Dmaven.javadoc.skip=false
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
