name: build-test-deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK and maven cache
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: "temurin"
          cache: maven

      - name: build and test
        continue-on-error: true
        run: ./mvnw clean verify


      - name: Publish to Github Packages
        run: ./mvnw deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # update dep graph for dependabot
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
