name: build - test - publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repository
      - uses: actions/checkout@v4

      - name: Set up JDK and maven cache
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: "temurin"
          cache: maven

      - name: checkstyle check
        continue-on-error: true
        run: ./mvnw clean verify

      - name: Test project
        run: mvnw test

      - name: Publish to Github Packages
        run: mvnw deploy

      # update dep graph for dependabot
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
